apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: tonearm
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.6.0
  image: tonearm/kafka:2.6.0-connect-8
  replicas: 1
  bootstrapServers: tonearm-kafka-bootstrap.kafka:9093
  tls:
    trustedCertificates:
      - secretName: tonearm-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    topic.creation.enable: "true"
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1