apiVersion: "kafka.strimzi.io/v1alpha1"
kind: "KafkaConnector"
metadata:
  name: pitcher-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: pitcher # replace with your strimzi cluster
spec:
  class: com.github.jcustenborder.kafka.connect.solr.CloudSolrSinkConnector
  tasksMax: 1
  config:
    topics: pitcher.track-info
    solr.zookeeper.hosts: zookeeper-client.zookeeper:2181
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry-cp-schema-registry.kafka:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry-cp-schema-registry.kafka:8081