apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "musicbrainz.fullname" . }}
  labels:
    {{- include "musicbrainz.labels" . | nindent 4 }}
data:
  postgres_host: "{{ .Values.postgres.host }}"
  postgres_port: "{{ .Values.postgres.port }}"
  postgres_user: "{{ .Values.postgres.user }}"
  postgres_database: "{{ .Values.postgres.database }}"
  redis_host: "{{ .Values.redis.host }}"
  redis_port: "{{ .Values.redis.port }}"