apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "musicbrainz.fullname" . }}-dbdump
  labels:
    {{- include "musicbrainz.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    {{- toYaml .Values.pvc.resources | nindent 12 }}
  storageClassName: {{ .Values.pvc.storageClassName }}