apiVersion: v1
kind: Secret
metadata:
  name: {{ include "musicbrainz.fullname" . }}
  labels:
    {{- include "musicbrainz.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres_password: "{{ .Values.postgres.password }}"
  replication_token: "{{ .Values.replicationToken }}"